<template>
  <div>
    <div class="flex flex-wrap justify-between items-center gap-4 mb-4"><div><h2 class="page-title">Fullfil Params</h2><p class="text-sm text-(--text-muted) m-0">Manage fullfil parameter entries</p></div><button type="button" class="add-button" @click="openCreate">+ Add Fullfil Params</button></div>
    <input v-model="search" type="search" placeholder="Search mapping, name, or notes..." class="search" />
    <div v-if="loading" class="state">Loading data&hellip;</div><div v-else-if="error" class="state error-text">{{ error }}</div>
    <template v-else>
      <div class="table-wrap"><table><thead><tr><th v-for="header in headers" :key="header">{{ header }}</th></tr></thead><tbody><tr v-if="filteredRows.length === 0"><td colspan="8" class="empty">No data.</td></tr><tr v-for="row in filteredRows" :key="row.id"><td>{{ row.id }}</td><td>{{ mappingName(row.fullfil_id) }}</td><td class="strong">{{ row.name }}</td><td>{{ row.value }}</td><td>{{ unitName(row.unit_id) }}</td><td>{{ row.notes || '-' }}</td><td>{{ formatDate(row.updated_at) }}</td><td><button class="action" @click="openEdit(row)">Edit</button><button class="delete-action" @click="confirmDelete(row)">Delete</button></td></tr></tbody></table></div>
      <div class="cards"><div v-if="filteredRows.length === 0" class="empty">No data.</div><div v-for="row in filteredRows" :key="row.id" class="card"><div class="flex justify-between"><strong>{{ row.name }}</strong><span>ID: {{ row.id }}</span></div><div class="card-copy">Fullfil Mapping: {{ mappingName(row.fullfil_id) }}<br />Value: {{ row.value }} {{ unitName(row.unit_id) }}<br />Notes: {{ row.notes || '-' }}</div><div class="flex justify-end gap-2"><button class="action" @click="openEdit(row)">Edit</button><button class="delete-action" @click="confirmDelete(row)">Delete</button></div></div></div>
    </template>
    <div v-if="actionError && !deleteTarget" class="error-text action-error">{{ actionError }}</div>
    <FullfilParamsForm :visible="showForm" :item="editing" :mappings="mappings" :units="units" :submitting="submitting" @submit="save" @cancel="closeForm" />
    <Teleport to="body"><div v-if="deleteTarget" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><div class="bg-(--surface) rounded-2xl shadow-xl w-full max-w-sm mx-4 p-6"><h3 class="font-bold text-(--text)">Delete Fullfil Params</h3><p class="text-sm text-(--text-muted) my-4">Delete this parameter? This action cannot be undone.</p><div v-if="actionError" class="error-text mb-3">{{ actionError }}</div><div class="flex justify-end gap-3"><button class="action" @click="deleteTarget = null">Cancel</button><button class="delete-action" :disabled="submitting" @click="remove">Yes, Delete</button></div></div></div></Teleport>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import FullfilParamsForm from './FullfilParamsForm.vue'
import { createFullfilParams, deleteFullfilParams, listFullfilMappings, listFullfilParams, listTypeOfUnits, updateFullfilParams } from '../model'
import { useToast } from '../../../../utils/toast'

const { show: showToast } = useToast(); const headers = ['ID', 'Fullfil Mapping', 'Name', 'Value', 'Unit', 'Notes', 'Updated At', 'Actions']
const rows = ref([]); const mappings = ref([]); const units = ref([]); const loading = ref(false); const submitting = ref(false); const error = ref(null); const actionError = ref(null); const search = ref(''); const showForm = ref(false); const editing = ref(null); const deleteTarget = ref(null)
const unitName = (id) => units.value.find((item) => Number(item.id) === Number(id))?.name || `#${id}`
const mappingName = (id) => mappings.value.find((item) => Number(item.id) === Number(id))?.name || `#${id}`
const formatDate = (value) => value ? String(value).replace(/\.\d+/, '').replace('T', ' ').replace('Z', '') : '-'
const filteredRows = computed(() => { const q = search.value.trim().toLowerCase(); return q ? rows.value.filter((row) => `${mappingName(row.fullfil_id)} ${row.name} ${row.notes || ''} ${unitName(row.unit_id)}`.toLowerCase().includes(q)) : rows.value })
async function load() { loading.value = true; error.value = null; try { const result = await Promise.all([listFullfilParams(), listFullfilMappings(), listTypeOfUnits()]); rows.value = result[0].data; mappings.value = result[1]; units.value = result[2] } catch (err) { error.value = err?.message || 'Failed to load data.' } finally { loading.value = false } }
function openCreate() { editing.value = null; actionError.value = null; showForm.value = true }; function openEdit(row) { editing.value = { ...row }; actionError.value = null; showForm.value = true }; function closeForm() { showForm.value = false; editing.value = null }
async function save(payload) { submitting.value = true; actionError.value = null; try { if (editing.value?.id) { await updateFullfilParams(editing.value.id, payload); showToast('Fullfil Params updated successfully.') } else { await createFullfilParams(payload); showToast('Fullfil Params created successfully.') }; closeForm(); await load() } catch (err) { actionError.value = err?.message || 'Failed to save data.' } finally { submitting.value = false } }
function confirmDelete(row) { deleteTarget.value = row; actionError.value = null }; async function remove() { submitting.value = true; actionError.value = null; try { await deleteFullfilParams(deleteTarget.value.id); deleteTarget.value = null; showToast('Fullfil Params deleted successfully.'); await load() } catch (err) { actionError.value = err?.message || 'Failed to delete data.' } finally { submitting.value = false } }; onMounted(load)
</script>

<style scoped>
.page-title { font-size:clamp(24px,2.5vw,36px); font-weight:600; line-height:1.1; color:var(--text); margin:0 0 .25rem; }.add-button { border:0; background:#16a34a; color:white; font-weight:600; font-size:.875rem; padding:.625rem 1.25rem; border-radius:.75rem; cursor:pointer; }.search { border:1px solid var(--border); border-radius:.5rem; padding:.5rem .875rem; margin-bottom:1rem; color:var(--text); background:var(--surface); outline:none; width:18rem; }.state { display:flex; justify-content:center; padding:4rem 0; color:var(--text-muted); font-size:.875rem; }.error-text { color:#ef4444; font-size:.75rem; }.table-wrap { background:var(--surface); border:1px solid var(--border); border-radius:.75rem; overflow:hidden; }.table-wrap table { width:100%; border-collapse:collapse; }.table-wrap th { padding:1rem .75rem; text-align:left; font-size:.7rem; color:var(--text-muted); background:var(--surface-muted); text-transform:uppercase; letter-spacing:.08em; }.table-wrap td { padding:1rem .75rem; font-size:.875rem; color:var(--text-muted); border-top:1px solid var(--border); }.strong { color:var(--text) !important; font-weight:600; }.empty { text-align:center; padding:2.5rem !important; }.action,.delete-action { border-radius:.5rem; padding:.375rem .75rem; font-size:.875rem; font-weight:600; cursor:pointer; }.action { border:1px solid var(--border); background:var(--surface); color:var(--text); }.delete-action { border:0; background:#fef2f2; color:#dc2626; margin-left:.5rem; }.cards { display:none; }.action-error { margin-top:.75rem; }
@media (max-width:1100px) { .table-wrap { display:none; }.cards { display:flex; flex-direction:column; gap:.75rem; }.card { padding:1rem; background:var(--surface); border:1px solid var(--border); border-radius:.75rem; color:var(--text-muted); }.card strong { color:var(--text); }.card-copy { font-size:.75rem; margin: .5rem 0 .75rem; } }
</style>
